Tech Task: Update readme with standard deploy process
tablexi/nucore-open pull request #2543
Opened 2021-03-10 18:12 UTC by giladshanan

# Release Notes

- Adds `latest_from_open` script
- Adds stage url
- Updates deployment steps

2021-03-10 23:05 UTC, giladshanan commented on doc/HOWTO_forks.md
> +After adding the `upstream` remote, you can use the `bin/latest_from_open` script to automate creating a new `latest_from_open_YYYYMMDD` branch.
```suggestion
After adding the `upstream` remote, you can use the `bin/latest_from_open` script to create a new `latest_from_open_YYYYMMDD` branch.
```

2021-03-11 03:10 UTC, rdunlop requested changes

2021-03-11 03:10 UTC, rdunlop commented on bin/latest_from_open
> +#!/bin/sh
This file is not executable. Please make it executable?

2021-03-23 13:46 UTC, giladshanan commented on doc/HOWTO_forks.md
> +After adding the `upstream` remote, you can use the `bin/latest_from_open` script to create a new `latest_from_open_YYYYMMDD` branch.
```suggestion
After adding the `upstream` remote, you can use the `bin/latest_from_open` script to create a new `latest_from_open_MMDDYYYY` branch.
```

2021-03-23 14:11 UTC, giladshanan commented
@rdunlop any further feedback?

2021-03-24 20:54 UTC, rdunlop approved these changes

2021-03-24 20:54 UTC, rdunlop commented on doc/HOWTO_forks.md
> +1. Deploy the new code using capistrano or helm/CircelCI (see below)
typo CircleCI

2021-04-15 17:10 UTC, KaraAJC approved these changes

2021-04-20 15:40 UTC, wangminghao commented on doc/HOWTO_related_repos.md
> +or just a few commmits with a cherry-picked branch.
You can either bring over....
or just a few commits...

2021-04-20 15:42 UTC, wangminghao commented on doc/HOWTO_related_repos.md
> +1. Run any relevant rake tasks
(e.g. new env variables, one-off data fix...)

2021-04-20 15:45 UTC, wangminghao commented on doc/HOWTO_related_repos.md
> +1. Open a new branch, either`latest_from_open_MMDDYYYY` or cherry-picked [(see below)](#creating-a-latest_from_open_mmddyyyy-branch)
please add a link to the cherry-pick section below

2021-04-20 15:47 UTC, wangminghao commented on doc/HOWTO_related_repos.md
> +1. Add a new remote called `upstream ` that points to the `nucore-open` repo
extra space

2021-04-20 15:49 UTC, wangminghao commented on doc/HOWTO_related_repos.md
> +The `bin/merge_describer` script only describes commits which include the parenthesized branch number,
Make this the first point - it feels that important

2021-04-20 15:58 UTC, wangminghao commented on doc/HOWTO_related_repos.md
> +The best way to bring in the changes from NU is by cherry-picking the individual
long discussion....

2021-04-20 16:01 UTC, wangminghao commented on doc/HOWTO_related_repos.md
> +
If there is a preferred deployment method? "Method may vary depending on which school"

2021-04-20 19:06 UTC, wangminghao approved these changes

2021-04-21 17:26 UTC, merged