155426 failed attempt lockout
tablexi/nucore-open pull request #2559
Opened 2021-03-24 16:05 UTC by wangminghao

https://pm.tablexi.com/issues/155426

- Devise set up for locking accounts with custom error message
- Set User as lockable
- Create LogEvent when User becomes locked

Error Message:
![lockout-error-message](https://user-images.githubusercontent.com/411614/112343026-2135f000-8c99-11eb-8abd-ed0ae8181bc1.png)

LogEvent:
![event_log](https://user-images.githubusercontent.com/411614/112343069-285cfe00-8c99-11eb-8b23-16776be21c74.png)

2021-03-24 16:30 UTC, rdunlop reviewed
I seem to recall discussion with the client that "doing a password reset should clear the locked-out state" so that if they did a reset-password, they could log in immediately.

Is this possible? desired?

2021-03-24 16:30 UTC, rdunlop commented on app/models/user.rb
> +    puts "\n========= HELLO"
probably don't need this

2021-03-24 17:00 UTC, wangminghao commented
> I seem to recall discussion with the client that "doing a password reset should clear the locked-out state" so that if they did a reset-password, they could log in immediately.
> 
> Is this possible? desired?

My impression was that the desired behavior was the "normal" devise behavior, but I don't have the client context. @giladshanan do you have insight into this?

2021-03-24 18:37 UTC, giladshanan commented
The goal here is to improve security with minimal effort and impact on users.  We have a couple of options here:
- the user waits 5 min
- use the `:email` or `:both` unlock strategy, which are unlocked by password reset (https://github.com/heartcombo/devise/issues/2090) 

I will check in with the client this afternoon.

2021-03-24 21:44 UTC, giladshanan commented
The client is in favor of the `:email` unlock strategy instead of the 5 min cool off.

2021-03-25 15:02 UTC, giladshanan requested changes
One small request, looks good!

2021-03-26 14:30 UTC, rdunlop approved these changes

2021-03-29 21:50 UTC, rdunlop approved these changes

2021-03-29 21:55 UTC, giladshanan approved these changes

2021-03-29 21:55 UTC, merged