Tech task: Allow setting encryption options
tablexi/nucore-open pull request #2582
Opened 2021-04-30 19:02 UTC by giladshanan

Cannot be set in ldap.yml because Net::LDAP expects symbol values:
 method: - :simple_tls or :start_tls
 tls_options: - Hash of options for that method

2021-04-30 21:14 UTC, rdunlop requested changes

2021-04-30 21:14 UTC, rdunlop commented on vendor/engines/ldap_authentication/lib/ldap_authentication.rb
> +  def self.additional_user_attributes
this looks like a bad merge..duplicating the lines above it.

2021-05-02 20:05 UTC, giladshanan commented on config/ldap.yml.template
> +  encryption_method: "" # either simple_tls or start_tls
```suggestion
  encryption_method: "" # optional - valid options are either simple_tls, start_tls, or ''
```

2021-05-03 18:18 UTC, rdunlop approved these changes

2021-05-03 20:29 UTC, merged

2021-05-04 15:04 UTC, joshea0 commented
I realize this is already merged, but I just took a look and this looks great! Thanks @giladshanan for figuring this out. This is a big improvement from my POV

2021-05-04 15:08 UTC, giladshanan commented
@joshea0 sure thing! I'm glad we found a way to get this working, and this will be more flexible for future use as well.