[#142306] Holiday access rules
tablexi/nucore-open pull request #2692
Opened 2021-08-03 19:40 UTC by giladshanan

# Release Notes

Allows setting holiday access restriction at the product level, and then allowing access at the level of scheduling group (ProductAcessGroup).

Still working on specs but wanted to get some feedback.

2021-08-03 19:42 UTC, giladshanan commented on app/views/admin/products/_product_fields.html.haml
> +    = f.input :requires_approval, as: :boolean, label: false, inline_label: text("hints.requires_approval"), input_html: { data: { disables: ".#{f.object.class.model_name.to_s.underscore}_allows_trai
This probably should be `.#{f.object.class.model_name.to_s.underscore}_restrict_holiday_access` - or the `= f.input :restrict_holiday_access` element should only be shown for Instruments

2021-08-03 19:43 UTC, giladshanan commented on app/views/holidays/index.html.haml
> +%table.table
I need to make some accessibility adjustments for this table

2021-08-03 19:44 UTC, giladshanan commented on app/views/holidays/shared/_tab.html.haml
> += tab t("pages.holidays"), holidays_path, sidenav_tab == "holidays"
This file isnt  being used

2021-08-03 19:44 UTC, giladshanan commented on app/views/product_access_groups/index.html.haml
> +      - if @product.restrict_holiday_access?
Not sure how I feel about hiding this column

2021-08-04 18:30 UTC, rdunlop reviewed
looking good

2021-08-04 18:30 UTC, rdunlop commented on db/migrate/20210803022837_create_holidays.rb
> +      t.datetime :date, null: false
I think that there should. be an index on this column in order to support the `.on` scope.

2021-08-12 16:14 UTC, rdunlop commented on app/support/holiday_validations.rb
> +  def holiday_accessible
The way that this concern is written, adds a lot of methods to the including-object.

It does not appear that you actually want/need to expose `holiday_accessible`, `user_restricted_on_holidays?`, etc to any users of the including object.

I propose extracting this logic into a real PORO.

doing so would have these benefits:
- Explicitly make clear which attributes of the including object are being used
- Allow for easier testing, by making the attributes explicit.

Example:

```ruby
module HolidayValidations
  extend ActiveSupport::Concern

  included do
    validate :holiday_accessible
  end

  def holiday_accessible
    # this makes explicit which attributes you are depending on
    holiday_validator = HolidayValidator.new(
                                        product: product,
                                        user: user
                                        event_start_date: event_start_date

    return unless holiday_validator.restricted?

    errors.add(:base, :holiday_access_restricted)
end

class HolidayValidator
  ....
  def restricted?
    return false unless starts_on_holiday?

    product.restrict_holiday_access? && user_restricted_on_holidays?
  end
  ...
end
```

2021-08-20 15:00 UTC, rdunlop requested changes

2021-08-20 15:00 UTC, rdunlop commented on vendor/engines/secure_rooms/app/services/secure_rooms/access_rules/holiday_access_rule.rb
> +    class HolidayAccessRule < BaseRule
I thought that we would need to reference this class from the `CheckAccess` list of rules, no?

2021-08-20 15:59 UTC, giladshanan commented on vendor/engines/secure_rooms/app/models/secure_rooms/occupancy.rb
> +    belongs_to :product
Good catch - this is left over from an earlier point when the occupancy was getting validated (like a reservation).  We're not calling the `holiday_access` method to validate occupancies at all, so we don't need this association.

2021-08-20 20:56 UTC, rdunlop approved these changes

2021-08-20 21:10 UTC, merged