[#152051] Fail gracefully when replacing account owner with existing member
tablexi/nucore-open pull request #2705
Opened 2021-08-18 17:52 UTC by mtorres27

# Release Notes

This PR adds error handling for attempts to replace an account owner with a user that is already an account member.

# Screenshot

![Screen Shot 2021-08-18 at 12 20 26 PM](https://user-images.githubusercontent.com/35459081/129947696-db83ec40-e3ed-468b-b912-fb652af6fab9.png)

2021-08-18 20:23 UTC, rdunlop approved these changes

2021-08-18 22:14 UTC, giladshanan requested changes
Looks good!  I am blocking on account of the controller specs since we are trying to move away from those.  Let me know what you think about my other suggestion.

2021-08-18 22:14 UTC, giladshanan commented on app/controllers/facility_account_users_controller.rb
>      if @account_user.persisted?
What do you think about adding a branch to the existing conditional like:
```suggestion
    if @account_user.nil?
      flash[:error] = text("create.existing_member_error", user: @user.full_name)
      redirect_to facility_account_members_path(current_facility, @account)
    elsif @account_user.persisted?
```
This logic isn't as specific but I find the expected outcomes easier to parse.  

You could also do something like:
```'
def existing_member_becoming_owner?
  create_params[:user_role] == AccountUser::ACCOUNT_OWNER &&
    @account.account_users.map(&:user_id).include?(@user.id)
end
```
to cover this specific case, but I'm ok with using the more specific error message to cover any nil account_user.
We can adjust in the future if we need to.

2021-08-18 22:14 UTC, giladshanan commented on spec/controllers/facility_account_users_controller_spec.rb
> +        context "from anything to owner" do
Can you add this as a simple system spec for this instead?  I should have mentioned this earlier but we are moving away from controller specs in the codebase.

2021-08-19 18:59 UTC, giladshanan approved these changes

2021-08-19 19:00 UTC, merged