Update mailer syntax
tablexi/nucore-open pull request #2913
Opened 2022-02-09 21:32 UTC by madcowley

# Release Notes

This updates the mailer syntax to use .with

https://pm.tablexi.com/issues/159818

2022-02-09 22:06 UTC, rdunlop requested changes

2022-02-09 22:06 UTC, rdunlop commented on app/controllers/concerns/csv_email_action.rb
> +      CsvReportMailer.with(to_address: email, report: report).delay.csv_report_email
Is `delay` the old way of doing `deliver_later`? Can we update this to use `deliver_later` (I don't know whether they are equivalent).

2022-02-11 03:20 UTC, rdunlop commented on app/controllers/concerns/csv_email_action.rb
> +      CsvReportMailer.with(to_address: email, report: report).csv_report_email.deliver_later
Perhaps this comment was here on purpose, and that's why we should stick with `.delay`? I think that I'd like @giladshanan to weigh in on this.

2023-07-26 20:13 UTC, giladshanan commented
We are running ruby 3 without these changes, closing

2023-07-26 20:13 UTC, closed without merging