Translation updates
tablexi/nucore-open pull request #3162
Opened 2022-09-20 20:25 UTC by jossim

Release Notes
This fixes spec failures in latest_from_open_20220919

# Release Notes

A one- or two-sentence explanation of what the change is and why, phrased for a non-technical audience. This should be copy-pasted as your commit message when the PR is merged. (Required)

Please preface your release note with "TECH TASK: " if the change is a technical task such as a gem upgrade or changes to a configuration file.

# Screenshot

Optional.

# Additional Context

Optional. Feel free to add/modify additional headers as appropriate, e.g. "Refactorings", "Concerns".

2022-09-21 02:34 UTC, giladshanan commented
Looking good, just a few spec failures

2022-09-22 15:59 UTC, giladshanan requested changes
A few small changes, looks good over all

2022-09-22 15:59 UTC, giladshanan commented on config/locales/en.yml
> +  name_or_sso_id: name, OID, or username
```suggestion
  Sso_id: NetID
  sso_id_downcase: NetID
  name_or_sso_id: name, NetID, or username
```

2022-09-22 15:59 UTC, giladshanan commented on config/locales/override/en.yml
>    # attributes:
attributes belongs nested under activerecord I believe

2022-09-22 15:59 UTC, giladshanan commented on spec/system/admin/moving_transactions_spec.rb
> +    click_button "Reassign #{chart_string_name_upcase}"
Should this be:
```suggestion
    click_button "Reassign #{chart_strings_name_upcase}"
```

2022-09-22 17:02 UTC, jossim commented on config/locales/override/en.yml
>    # attributes:
Indeed! Done

2022-09-22 20:31 UTC, giladshanan approved these changes

2022-09-22 21:00 UTC, merged