[#161127] Docs tab for users (#238)
tablexi/nucore-open pull request #3325
Opened 2023-01-13 20:55 UTC by jossim

# Release Notes

This adds a document tab for users that admins can use to upload files associated with a user.

This PR is a cherry-picked of https://github.com/Oregon-State/nucore-osu/pull/238

# Screenshot

![Screen Shot 2023-01-09 at 4 53 31 PM](https://user-images.githubusercontent.com/624487/211424457-0d21bde9-0bcc-4b76-a86b-d7e0d024d7fe.png)

2023-01-13 21:18 UTC, giladshanan reviewed
@jossim did you run the migration locally?  I think the specs are failing because the timestamp version in `schema.rb` should match the filename of the most recent migration file:
```
ActiveRecord::Schema.define(version: 2022_12_12_231558) do
```

2023-01-14 02:36 UTC, giladshanan requested changes

2023-01-14 02:36 UTC, giladshanan commented on db/schema.rb
> +    t.string "revenue_account", null: false
@jossim this doesn't look right.  I think your local db might be in a funky state. See https://github.com/tablexi/nucore-open/pull/3137

2023-01-17 19:09 UTC, giladshanan approved these changes
One small nitpick

2023-01-17 19:09 UTC, giladshanan commented on app/views/admin/shared/_tabnav_users.html.haml
> +  = tab "Docs", facility_user_user_file_uploads_path(current_facility, @user), secondary_tab == "docs"
Can you use the translation file here?
```suggestion
  = tab t(".user_docs"), facility_user_user_file_uploads_path(current_facility, @user), secondary_tab == "docs"
```

2023-01-17 19:26 UTC, giladshanan approved these changes

2023-01-17 19:28 UTC, merged

2023-02-10 15:21 UTC, stevens101 commented
It looks like the documents table column headings don't align with the data in the rows. For example the "File" column is actually the Delete column. Might need another th tag.