Change cross-core orders header
tablexi/nucore-open pull request #4637
Opened 2024-10-11 19:15 UTC by diebas

# Release Notes

In the order show view accessed through the facility management menu, there's a section with a "Cross-core header". This header doesn't describe the menu's function correctly. The menu allows adding cross-core products to an order but it also allows to add products from the same facility as well and many users use it this way.

# Screenshot

Before:
<img width="1265" alt="Screenshot 2024-10-11 at 4 13 39 PM" src="https://github.com/user-attachments/assets/f356556b-783a-4f1c-87d8-abadb73d008d">

After:
<img width="1246" alt="Screenshot 2024-10-11 at 4 13 01 PM" src="https://github.com/user-attachments/assets/ccf08302-4248-4933-8f70-35094b783447">

# Additional Context

I suggest a less specific header: "Add Product to Selected Order"

Didn't opt for a dynamic header as the header is defined in the HTML view structure. I don't think moving the logic to the javascript code to change it dynamically when selecting a facility in the menu dropdown is worth the effort as it's just a header and the action button already provides this information dynamically to the user.

2024-10-11 19:55 UTC, LeticiaErrandonea reviewed
Left a comment.

Thanks for the complete PR description! Much appreciated

2024-10-11 19:55 UTC, LeticiaErrandonea commented on config/locales/views/en.facility_orders.yml
> +        add_product_order_header: "Add Product to Selected Order"
I think I'd go with just "Add to order"

2024-10-11 19:59 UTC, diebas commented on config/locales/views/en.facility_orders.yml
> +        add_product_order_header: "Add Product to Selected Order"
sure, sounds good to me

2024-10-11 20:28 UTC, LeticiaErrandonea approved these changes

2024-10-11 20:30 UTC, giladshanan requested changes
Can you add the ticket number to the PR title?

2024-10-11 20:34 UTC, giladshanan requested changes

2024-10-11 20:34 UTC, giladshanan commented on app/views/facility_orders/show.html.haml
> +%h2= t("views.facility_orders.show.add_to_order_header")
Could you check if the order is cross core, then select a different translation based on that?

2024-10-11 20:37 UTC, giladshanan commented on app/views/facility_orders/show.html.haml
> +%h2= t("views.facility_orders.show.add_to_order_header")
For example: Add to Order or Add to Cross Core Order

2024-10-14 13:50 UTC, giladshanan approved these changes
Looks good!  I left one suggestion, nothing blocking

2024-10-14 13:50 UTC, giladshanan commented on app/views/facility_orders/show.html.haml
> +%h2= t(@order.cross_core_project_id.present? ? "views.facility_orders.show.add_to_cross_core_order_header" : "views.facility_orders.show.add_to_order_header")
Small suggestion - I find it easier to read this code broken up into 2 lines:
```suggestion
- subheader_key = @order.cross_core_project_id.present? ? "views.facility_orders.show.add_to_cross_core_order_header" : "views.facility_orders.show.add_to_order_header"
%h2= t(subheader_key)
```

2024-10-14 14:43 UTC, LeticiaErrandonea commented on app/views/facility_orders/show.html.haml
> +- subheader_key = (@order.cross_core_project_id.present? ? "views.facility_orders.show.add_to_cross_core_order_header" : "views.facility_orders.show.add_to_order_header")
nit: `@cross_core_project` is already set and used a little bit above. Can you update this to use that var?

2024-10-14 15:16 UTC, merged